---
title: "Untitled"
output: html_document
---



```{r}
universal_adapter="AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT"
index_adapter_suffix="ATCTCGTATGCCGTCTTCTGCTTG"
c(universal_adapter,index_adapter_suffix) %>%
  str_sub(-10)
```

```{r}

qc_dir="/workspace/nci_r25/qc"
Sys.setenv(ADAPTERS="adapter_seqs.fasta")
Sys.setenv(FASTQ_DIR="/workspace/nci_r25/sra_data")
Sys.setenv(TRIMMED_DIR="/workspace/nci_r25/trimmed")
Sys.setenv(QC_DIR=qc_dir)
Sys.setenv(TOTAL_THREADS="55")

sra_dir %>%
  list.files(pattern=".fastq.gz$", full.names=TRUE) %>%
  paste(collapse = " ") %>%
  Sys.setenv(FASTQS=.)

dir.create(qc_dir)
```

```{bash}
set -u

mkdir -p $TRIMMED_DIR
for R1_FASTQ in ${FASTQ_DIR}/*_1.fastq.gz; do
  FASTQ_BASE=$(basename $R1_FASTQ _1.fastq.gz)
  echo $FASTQ_BASE
  fastq-mcf \
    $ADAPTERS \
    ${FASTQ_DIR}/${FASTQ_BASE}_1.fastq.gz \
    ${FASTQ_DIR}/${FASTQ_BASE}_2.fastq.gz \
    -o ${TRIMMED_DIR}/${FASTQ_BASE}_1_trimmed.fastq.gz \
    -o ${TRIMMED_DIR}/${FASTQ_BASE}_2_trimmed.fastq.gz \
    -q 20 -x 0.5 > ${TRIMMED_DIR}/${FASTQ_BASE}_fastqmcf_out.txt
done
```


```{bash engine.path="/bin/bash"}
fastqc --quiet --threads $TOTAL_THREADS $FASTQS --outdir $QC_DIR
```

```{bash engine.path="/bin/bash"}
multiqc --force $QC_DIR --outdir ${QC_DIR} --filename multiqc_some.html
```


```{bash}
set -u
fastq-mcf \
  $ADAPTERS \
  /workspace/nci_r25/sra_data/SRR12804473_1.fastq.gz \
  -o /workspace/nci_r25/sra_data/SRR12804473_1_trimmed.fastq.gz \
  -q 20 -x 0.5
```

```{bash}
set -u
fastq-mcf \
  $ADAPTERS \
  /workspace/nci_r25/sra_data/SRR12804473_2.fastq.gz \
  -o /workspace/nci_r25/sra_data/SRR12804473_2_trimmed.fastq.gz \
  -q 20 -x 0.5
```

```{bash}
set -u
fastq-mcf \
  $ADAPTERS \
  /workspace/nci_r25/sra_data/SRR12804473_1.fastq.gz \
  /workspace/nci_r25/sra_data/SRR12804473_2.fastq.gz \
  -o /workspace/nci_r25/sra_data/SRR12804473_1_trimmed.fastq.gz \
  -o /workspace/nci_r25/sra_data/SRR12804473_2_trimmed.fastq.gz \
  -q 20 -x 0.5
```

```{bash}
set -u

fastq-mcf \
  $ADAPTERS \
  /data/sra_fastqs/SRR12933525.fastq.gz \
  -o /workspace/nci_r25/sra_data/SRR12933525_trimmed.fastq.gz \
  -q 20 -x 0.5
```



