
# Introduction to Unix and bash
## Author: Janice McCarthy

## What is an operating system?

Most of you probably know that Unix (Linux), like Windows and MacOS, is an operating system (OS). An operating system is essentially the interface between applications (such as Word or your browser) and the computer itself (devices, memory, etc.) 

### We usually interact with the OS using a Graphical User Interface (GUI).

Those are the 'windows' that made microsoft into the giant it is today. We open windows into the OS (formally known as DOS). We point and click to find files, open programs, etc. This has the advantage that it is natural for the user. A disadvantage is that pointing and clicking isn't exactly 'reproducible'. We don't have a record of everything we have done - and that is something we really want when analyzing data.

### Another way - the command line

Unix, Windows and MacOS all have command line interfaces. We can access them via 'terminal' windows. The Jupyter environment offers two different ways to use the command line (in our case, we will use the bash shell - more on that later). There is a terminal window under the tab on the left hand side, but there is also a bash *kernel*, so that you can write commands in a notebook code cell and have them interpreted as unix commands. You will learn to use both in this course.

### The unix command line interpreter is an interactive program

The interpreter parses the strings you enter and calls the appropriate executable program. There are different versions of this program, of which 'bash' is one. 'sh' was the original version, written in the 1970s by Ken Thompson. It was updated over the years and finally completely re-written in 1979 by Stephen Bourne. In 1989, another shell was built on the Bourne 'sh' - and it was named 'bash' - for Bourne Again sh. There are several other flavors, but we will be using bash.

#### sh? Why the hush?

sh is short for 'shell'. The reason for this terminology is because you can think of these programs as hosting an environment (variables can be saved and referred to later, among other things). But shells can run any program, including other shells. So there is a notion of 'inheritance' from the environment - each subsequently called shell is contained in the other.

<!-- #region -->
### The main features of a shell

The basic features a shell program has are some basic programming constructs (loops, conditionals, variables etc.) and ways to link programs together (pipes and redirections). Before we examine those, let's get a little experience working in the command line. We'll learn how to:

    - print the current directory (and what does 'current' directory mean?)
    - list the contents
    - make a new directory
    - copy and rename files
    - examine the content of (text) files
    - Use tab completion
    - Use meta characters
    
## Early exploration

In the following, we will use the terminal screen to explore some of the aspects of the shell. Then, in the next session, we will begin to study the shell more methodically, using the notebook interface.


We'll work through the following commands

#### Command glossary

- `ls` (list)
- `ls -l` (long list)
- `ls -t` (time)
- `ls -r` (reverse sort order)
- `mkdir` (make directory)
- `cd` (change directory)
- `cp` (copy file)
- `mv` (rename file)
- `pwd` (print working directory)

And introduce 'globs'

#### Globs

- `*` (match everything)
- `?` (match one character)


### Exercises - basic commands

From the terminal screen

1. Print the current directory
2. Make a directory called 'mydir'
3. Change directory to 'mydir'
4. Create a notebook using the Jupyter menu and  copy it to mydir.
5. Make another copy of this notebook named 'copy'
6. List the contents of the directory
7. List the contents of the directory in long form with permissions and modification times
8. Sort the list by time.
9. Sort the list in reverse order.
10. List all files in the parent directory.
<!-- #endregion -->

<!-- #region -->
### Linking programs together - pipes and I/O redirection

When working at the command line, it is very common (and useful!) to link programs together using 'redirection' and 'piping'. The pipe is so useful, it has been incorporated into R programming, especially when munging and wrangling data. 

#### I/O streams

So, what are we 'redirecting'? There are three standard I/O streams in Unix:

- `stdin` or standard input - usually the keyboard
- `stdout` or standard output - usually the terminal screen
- `stderr` or standard error. This is beyond our scope.

#### I/O redirections using `|`, `>`, `<`

A program's input and output can be redirected from the standard streams in many powerful ways:

- We can store a program's output in a file to be saved. (`>`).
- We can direct a program to take input from a file rather than the keyboard (`<`).
- We can direct a program's output to be another program's input (`|`). This allows linking of several programs to form a workflow.

#### Examples

`echo "hello world"`

`echo "hello world" > hw.txt`

`echo "hello again" >> hw.txt`

`cat hw.txt`

`echo "world" > w.txt`

`grep "world" *.txt`

`grep "hello" *.txt`

`ls -l /etc`

`ls -l /etc |more`


#### Exercises

1. The `ps -aef` command shows all processes currently running. Use `|` and the program `grep` to find the processes you are running (your user name is 'joyvan')

2. Create a list with the filenames in the current directly using `ls` and `>`. Use `cat` to see the contents. 

3. What happens if you repeat the above using `>>`?

<!-- #endregion -->
# Working with Unix

## Author: Cliburn Chan
## Edited by: Janice McCarthy

## Bash kernel
In the previous unit, we used the terminal window to type commands to the bash shell. The Jupyter notebook interface allows us to create bash code cells, so that we can create a reproducible series of commands. We can also write 'shell scripts', which are text files that can be read by bash, but as we will do the entire RNA analysis pipeline using notebooks, those are beyond our scope.

In this unit, we'll re-inforce some of the last unit. The following commands are very useful:

## File and directory navigation

```
pwd   Print working direcoory
ls    List files
mkdir Make directory
rmdir Remove directory
cd    Change directory
rm    Remove file
touch Create empty file
cp    Copy file
mv    Move file
```

### Where am I?


```{bash}
pwd
```

### Why does it matter where I am? 

The concept of the 'working directory' comes from the way that bash locates files. The default place for bash to look is in the 'working directory'. We saw earlier that you can 'change directories' using `cd`. 


### List files

We can list the files in the 'current' or working directory using `ls`.


```{bash}
ls
```

Some files are 'hidden' (by default, `ls` does not list files whose names start with '.')

```{bash}
ls -a
```

```{bash}
ls -l
```

Fields returned by `ls -l`:

- Permissions
- Number of hardlinks
- File owner
- File group
- File size
- Modification time
- Filename

Interpreation of permissions
```
-rw-r--r--

-   Regular file
rw- Owner has Read and Write permission
r-- Group has Read permission
r-- Other has Read permission
```

### Globbing


```{bash}
ls *Rmd
```

```{bash}
ls U*
```

```{bash}
ls *nix??_*Exercises*
```

### Make directories


```{bash}
mkdir a
mkdir a/b
mkdir a/b/c
```


```{bash}
ls
```

```{bash}
ls -R
```

```{bash}
ls -l
```

```{bash}
rmdir a/b/c
rmdir a/b
rmdir a
```


```{bash}
ls
```

### Making nested directories in one step


```{bash}
mkdir -p a/b/c a/b/d a/b/e
```

### Create empty files


```{bash}
touch a/b/c/foo.txt a/b/d/bar.txt a/b/e/baz.txt
```


```{bash}
ls -R
```

```{bash}
cp a/b/c/foo.txt foo_copy1.txt
cp a/b/c/foo.txt a/foo_copy2.txt
cp a/b/c/foo.txt a/b/foo_copy3.txt
```


```{bash}
ls -R
```

```{bash}
mv a/b/c/foo.txt a/b/c/oof.txt
```


```{bash}
ls a/b/c
```

```{bash}
mv a/b/c/oof.txt oof.txt
```


```{bash}
ls a/b/c
```


```{bash}
ls 
```

### Navigating between directories


```{bash}
cd a/b/
```


```{bash}
ls
```

#### Deleting a file


```{bash}
rm foo_copy3.txt
```


```{bash}
ls
```

### Move back


```{bash}
pwd
```

```{bash}
cd ..
```


```{bash}
pwd
```

```{bash}
cd ..
```


```{bash}
pwd
```

```{bash}
cd a/b/c
```


```{bash}
pwd
```

```{bash}
cd ../../../
```


```{bash}
pwd
```

#### Go home


```{bash}
cd ~
```


```{bash}
pwd
```

#### Go last position


```{bash}
cd -
```

### Pathnames

We've already used pathnames, but didn't point them out. We have seen that bash looks in the current directory for files, and if we look for a file that is not in the current directory, but exists elsewhere, we'll get an error:

```{bash}
ls b
```

Bash doesn't see 'b' because it's not in the current directory. We can give its (relative) path name and bash can find it:

```{bash}
ls a/b
```

Because 'b' is a directory, `ls` displays its contents.


### Quick and dangerous recursive deletion


```{bash}
rm -r a
```


```{bash}
ls 
```

I can see from the `ls` command that the only files with the extension '.txt' are `foo_copy1.txt` and `oof.txt`.  I want to remove them, and to do that I can use `rm *.txt`. But I get a little paranoid when using `*` with `rm`, so I will often check first, giving the exact string first to `ls`.

```{bash}
ls *.txt
```

```{bash}
rm *.txt
```


```{bash}
ls
```

## Exercises

1. Create the following structure including empty files using `mkdir` and `touch` commands.

```
cryptococcus
    data
        fake1.fq
        fake2.fq
    notebooks
        my_analysis.R
        your_analysis.R
        fake3.fq
    results
        table1.csv
        table2.csv
        fig1.png
        fig2.png
```


```{bash}

```

2. Navigate into the folder `cryptococcus/results` and find the size of `fig1.png`. Next make a copy of `table2.csv` with name `table3.csv`. Finally, navigate back to the same directory where this notebook is found.


```{bash}

```

3. Move the file `fake3.fq` from the `notebooks` to the `data` directory.


```{bash}

```

4. List all files recursively that have the extension `.R`


```{bash}

```

5. Delete the results directory and all files in it (non-recursively).


```{bash}

```

6. Delete the `cryptococcus` directory recursively.


```{bash}

```
# File I/O

## Author: Cliburn Chan
## Edited by: Janice McCarthy

## Creating a file

### Using redirection


```{bash}
ls
```

```{bash}
echo "Hello Unix"
```

```{bash}
echo "Hello Unix" > foo.txt
```

### Using `heredocs`

`heredocs` allows us to create a multi-line file from the command line. It's probably not very useful for this course itself, but it is useful to create the following example:

```{bash}
cat > bar.txt << EOF
This old man he played one
He played knick knack on my thumb
EOF
```

## View file contents


```{bash}
cat foo.txt
```

```{bash}
cat bar.txt
```

## More redirection


```{bash}
echo "I love {bash}" >> foo.txt
```


```{bash}
cat >> bar.txt << EOF
This old man he played two
He played knick knack on my shoe
EOF
```

## View file contents


```{bash}
cat foo.txt
```

```{bash}
cat bar.txt
```

## More redirection


```{bash}
echo "Many people hate {bash}" > foo.txt
```

Oops, you've over-written the original contents of foo.txt and they are lost forever.


```{bash}
cat foo.txt
```

### Safety

If your file contents are precious and should not be changed (e..g raw data), you can change permisions to read-only.


```{bash}
ls -l foo.txt
```

```{bash}
chmod -w foo.txt
```


```{bash}
ls -l foo.txt
```

```{bash}
echo "Try to overwrite" > foo.txt
```

## Redirecting command output


```{bash}
ls
```

```{bash}
ls > contents.txt
```


```{bash}
cat contents.txt
```

### Piping


```{bash}
head -3 contents.txt | wc -c
```

```{bash}
head -3 contents.txt | wc -c > word_count.txt
```


```{bash}
cat word_count.txt
```

### Clean up


```{bash}
ls
```
