# Unix Variables

## Safety - Disable default variables

The default behavior is to assign the empty string to undeclared variables. This is a problem because it makes mis-spelled variables hard to detect.


```{bash}
echo $DOES_NOT_EXIST
```
```{bash}
set -u
```


```{bash}
echo $DOES_NOT_EXIST
```

## Assigning variables


```{bash}
FILENAME="temp.txt"
```


```{bash}
echo $FILENAME
```

```{bash}
echo "Some stuff" > $FILENAME
```


```{bash}
cat $FILENAME
```

## Common mistakes

You must not have spaces on either side of `=` in a variable assignment.


```{bash}
FILENAME = "temp.txt"
```

Unix interprets this as: run a command called `FILENAME`


```{bash}
FILENAME ="temp.txt"
```

Unix interprets this as: Assign space to the variable FILENAME then run a program called `temp.txt`


```{bash}
FILENAME= "temp.txt"
```

## Using a variable


```{bash}
PREFIX="Gene"
```


```{bash}
echo $PREFIX
```

```{bash}
echo $PREFIX001
```

If you surround the variable name with curly braces, you can concatenate names.


```{bash}
echo ${PREFIX}001
```

## Assigning command outputs to variables

To caputre the output of a command, use `$(command)`


```{bash}
FILES=$(ls)
```


```{bash}
echo $FILES
```

```{bash}
grep -in "unix" $FILES | head -5
```

We can also use the anonumous caputre form.


```{bash}
grep -in "unix" $(ls) | head -5
```

You may sometimes see this old backticks form. It is equivalent although modern usage seems to favor the `$(command)` from.


```{bash}
grep -in "unix" `ls` | head -5
```

## Using variables in loops


```{bash}
for FILE in $(ls *txt)
do
    wc -c $FILE
done
```

```{bash}
for FIB in 1 1 2 3 5
do
    echo $FIB
done
```

## Single and double quotes

Variables are not evaluated within single quotes, but they are within double quotes.


```{bash}
FOO=42
echo '$FOO'
```

```{bash}
FOO=42
echo "$FOO"
```

## Environment variables

You can see what variables are visible in the environment with `env`


```{bash}
env | head -5
```

```{bash}
echo $HOME
```

To make a variable visible in the general environment so that other programs can use it, you need to `export` it.


```{bash}
env | grep EXPORTED_VARIABLE
```




```{bash}
export EXPORTED_VARIABLE="Hello, Unix"
```


```{bash}
env | grep EXPORTED_VARIABLE
```

Now remove the environment variable.


```{bash}
unset EXPORTED_VARIABLE
```


```{bash}
env | grep EXPORTED_VARIABLE
```
<!-- #region -->
# The Unix Shell: Programming Constructs


## loops
 
 - **for loops** 
 
    Use for iterating over a fixed number of items (may be unknown at time of coding)
   
    `for i in $( ls ); do`
            echo item: $i
      `done`
        
 - **while loops**
 
     Use for iterating until a certain condition is met
     
    `while true; do`
       echo 'hello' 
      `done`
 
<!-- #endregion -->

### Examples

```{bash}
#This loop lists the files in the current directory and then iterates over them, printing out each filename
for i in $(ls); do
    echo item: $i
done
```

```{bash}
# Why doesn't this work?

for i in $(ls -l); do
    echo item: $i
done
```

```{bash}
for letter in {a,b,c,d}; do
    echo $letter
done
```

```{bash}
# What happens here?

for letter in a,b,c,d; do
    echo $letter
done
```

```{bash}
x=1
while [ $x -le 5 ]
do
  echo "Welcome $x times"
  x=$(( $x + 1 ))
done
```

   WARNING: Beware of infinite loops! They are easy to make with `while` (you can do it with `for` loops too, but `while` is just easier). You 


## Conditionals (sometimes called 'flow control')
  
  - Simple **if-then**
  
 `if [ "foo" = "foo" ]; then`
         echo expression evaluated as true
     `fi`
            
  - **if-then-else**
  
   `if [ "foo" = "foo" ]; then`
               echo expression evaluated as true
    `else`
               echo expression evaluated as false
    `fi`

```{bash}
a=1

if [ $a = 1 ]; then
    echo "a is 1"
fi

```

```{bash}
a=1

if [ $a = 2 ]; then
    echo "a is 2"
else
    echo "a is not 2"
fi
```

```{bash}
a=1
b=2

if [ $a = 2 ] | [ $b = 2 ]; then
    echo "a or b is 2"
fi
```

## Exercises for loops and conditionals

1. Write a for loop to repeat 'hello world' 10 times. Print the number of iteration so the output looks like:
    1. 1 hello world
    2. 2 hello world
    3. 3 hello world 
   
   etc.
 
2. Modify the above to add the word 'again' as many times as the number of current iterations:
   1. 1 hello world
   2. 2 hello world again
   3. 3 hello world again again
   
   etc.
   
3. Modify 2 to stop after 3 iterations, after printing 'enough already'.

4. Modify 3 to use a while loop.

5. Write a conditional statement to check whether a variable is greater than 10 (-gt is greater than) and print "this variable is greater than 10" if it is, or "this variable is not greater than 10" if it is not.

```{bash}

```
