# File I/O

## Author: Cliburn Chan
## Edited by: Janice McCarthy

## Creating a file

### Using redirection


```{bash}
ls
```

```{bash}
echo "Hello Unix"
```

```{bash}
echo "Hello Unix" > foo.txt
```

### Using `heredocs`

`heredocs` allows us to create a multi-line file from the command line. It's probably not very useful for this course itself, but it is useful to create the following example:

```{bash}
cat > bar.txt << EOF
This old man he played one
He played knick knack on my thumb
EOF
```

## View file contents


```{bash}
cat foo.txt
```

```{bash}
cat bar.txt
```

## More redirection


```{bash}
echo "I love {bash}" >> foo.txt
```


```{bash}
cat >> bar.txt << EOF
This old man he played two
He played knick knack on my shoe
EOF
```

## View file contents


```{bash}
cat foo.txt
```

```{bash}
cat bar.txt
```

## More redirection


```{bash}
echo "Many people hate {bash}" > foo.txt
```

Oops, you've over-written the original contents of foo.txt and they are lost forever.


```{bash}
cat foo.txt
```

### Safety

If you file contents are precious and should not be changed (e..g raw data), you can change permisions to read-only.


```{bash}
ls -l foo.txt
```

```{bash}
chmod -w foo.txt
```


```{bash}
ls -l foo.txt
```

```{bash}
echo "Try to overwrite" > foo.txt
```

## Redirecting command output


```{bash}
ls
```

```{bash}
ls > contents.txt
```


```{bash}
cat contents.txt
```

### Redirecting error messages


```{bash}
cat foobar.txt
```

```{bash}
cat foobar.txt > error.txt
```

```{bash}
ls e*txt
```

```{bash}
cat error.txt
```

### Why is error.txt it empty?

The standard `>` is  short for `1>` which means re-direct the standard output stream.


```{bash}
cat foobar.txt 1> stdout.txt
```

```{bash}
cat stdout.txt
```

```{bash}
cat foobar.txt 2> stderr.txt
```
```{bash}
cat stderr.txt
```

You can redirect to both.


```{bash}
cat foobar.txt > results.txt 2> errors.txt
```
```{bash}
cat results.txt
```


```{bash}
cat errors.txt
```

You can also redirect both streams to the same file with `&>`.


```{bash}
cat foobar.txt &> combined.txt
```
```{bash}
cat combined.txt
```

### Simple text operations


```{bash}
cat contents.txt
```

```{bash}
head -3 contents.txt
```

```{bash}
tail -3 contents.txt
```

```{bash}
wc contents.txt
```

```{bash}
wc -l contents.txt
```

```{bash}
wc -w contents.txt
```

```{bash}
wc -c contents.txt
```

If you don't want the filename, force it to read from standard input.


```{bash}
wc -c < contents.txt
```

### Piping


```{bash}
head -3 contents.txt | wc -c
```

```{bash}
head -3 contents.txt | wc -c > word_count.txt
```


```{bash}
cat word_count.txt
```

### Clean up


```{bash}
ls
```

### Fancy globbing


```{bash}
shopt -s extglob
```

Specifying what NOT to list.


```{bash}
ls !(*.Rmd)
```

```{bash}
ls !(*.txt)
```

```{bash}
ls *{.txt,.Rmd}
```

### Clean up


```{bash}
rm -f !(*.Rmd)
```

```{bash}
ls
```

## Exercises

1. Create 3 files with the same contents (say `lsd1.txt`, `lsd2.txt`, `lsd3.txt`)

```
Two of the most famous products of Berkeley are LSD and Unix. 
I don’t think that this is a coincidence.
```

using 

- Echo
- A HereDoc


```{bash}

```

2. Count the number of words in the second sentence only of lsd1.txt


```{bash}

```
