# Using `dplyr` for data manipulation

**Description**

```
dplyr provides a flexible grammar of data manipulation. It’s the next iteration of plyr, focused on tools for working with data frames (hence the d in the name).
```

If you look at [`dplyr` docs](https://cran.r-project.org/web/packages/dplyr/dplyr.pdf), there is a rich collection of data manipulaiton verbs provided. However, most common tasks can be accomplished with just 6 verbs that we will cover in this session:

```
select
filter
mutate a
arrange
summarize
group_by
```

We will also see how to construct data manipulation "sentnces" by using these versb togetehr wtih `pipes`.


```R
library(tidyverse)
```

## Data


```R
path='../data/hts_2018_data/2018_pilot_metadata_anon.tsv'
```


```R
getwd()
```


```R
df <- read_tsv(path)
```


```R
names(df)
```

### Fix names to be consistent

Note that some names use spaces between words and others use underscores. Le'ts fix this.


```R
names(df) <- str_replace_all(names(df), c('[:space:]+' = '_'))
```


```R
names(df)
```


```R
dim(df)
```

Note: Drop some columns so table fits in browser


```R
df <- df[, c(2:5, 8:15)]
```


```R
dim(df)
```


```R
sample_n(df, 3)
```


```R
summary(df)
```

### Fixing fake numeric columns

Note that `RNA_sample_num`, `Replicate` and `library#` are really discrete `factors` rather than numbrs.  As `#` is not allowed in an R variable name, we need to use backticks for `library#`. (Alternatively, we cna reame to something like `library_num`). 


```R
df %>% mutate(
    RNA_sample_num=factor(RNA_sample_num), 
    Replicate=factor(Replicate),
    `library#`=factor(`library#`)
) %>% 
select_if(is.factor) %>%
names
```

After checking that the transformation worked, we can save the transformed data.frame.


```R
df <- df %>% mutate(
    RNA_sample_num=factor(RNA_sample_num), 
    Replicate=factor(Replicate),
    `library#`=factor(`library#`)
)
```

## 0. Pipe


```R
df %>% head(10) %>% tail(3)
```

Note that the above result can also be achieved with `slice`


```R
df %>% slice(8:10)
```

## 1. Select columns


```R
df %>% select(1:3) %>% head(3)
```


```R
df %>% select(c(1,3,5)) %>% head(3)
```


```R
df %>% select(c('RNA_sample_num', 'Media')) %>% head(3)
```

### Dropping columns


```R
df %>% select(-((1:10))) %>% head(3)
```

### Selecting using string operations


```R
df %>% select(ends_with('person')) %>% head(3)
```


```R
df %>% select(starts_with('i')) %>% head(3)
```


```R
df %>% select(contains('primer')) %>% head(3)
```


```R
df %>% select(matches('.*_.*')) %>% head(3)
```

### Renaming columns with select


```R
df %>% 
select(c('method' = 'enrichment_method', 
         'fold.change' =  'concentration_fold_difference')) %>% 
head(3)
```

### Scoped variants


```R
df %>% select_if(is.numeric) %>% head(3)
```


```R
df %>% 
select_at(c('enrichment_method', 
            'concentration_fold_difference'), toupper) %>%
head(3)
```


```R
df %>% select_all(tolower) %>% head(3)
```

## 2. Filter rows


```R
unique(df$Media)
```

### Equality and inequality conditions


```R
df %>% filter(Media == 'TC') %>% head(3)
```


```R
df %>% filter(concentration_fold_difference > 3) %>% head(3)
```

### Combining conditions


```R
df %>% 
filter(Media != 'TC', 
       concentration_fold_difference > 3) %>%
head(3)
```


```R
df %>% 
filter(Media == 'TC' |
       concentration_fold_difference > 3) %>%
head(3)
```

### Filtering on string conditions


```R
df %>% filter(str_length(Media) == 3) %>% head(3)
```


```R
df %>% filter(str_detect(i7_index, '^A.+')) %>% head(3)
```

## 3. Arrange in ascending or descening order


```R
df %>% arrange(concentration_fold_difference) %>% head(3)
```


```R
df %>% arrange(desc(concentration_fold_difference)) %>% head(3)
```


```R
df %>% 
arrange(Replicate, 
        desc(concentration_fold_difference))%>% 
head(3)
```

### Using `top_n`


```R
df %>% top_n(3, concentration_fold_difference)
```


```R
df %>% top_n(3, desc(concentration_fold_difference))
```

## 4. Mutate values


```R
df %>% 
select(RNA_sample_num, concentration_fold_difference) %>%
mutate(concentration_difference=2^concentration_fold_difference) %>%
head(3)
```


```R
df %>%
transmute(concentration_difference=2^concentration_fold_difference) %>% 
head(3)
```

## 5. Summarize


```R
df %>% summarize(avg_fold_change=mean(concentration_fold_difference),
                 min_fold_change=min(concentration_fold_difference),
                 max_fold_change=max(concentration_fold_difference))
```


```R
df %>% summarize_if(is.numeric, mean)
```

## Group_by

`summariz`e is most useful when used with `group_by`


```R
df %>% 
group_by(Media, Strain, enrichment_method) %>%
summarize(mean_fold_diff=mean(concentration_fold_difference))
```


```R
df %>% 
group_by(Media, Strain, enrichment_method) %>%
summarize_if(is.numeric, mean) 
```


```R
df %>% 
group_by(Media, Strain) %>%
summarize_if(is.numeric, funs(mean, sd))
```

What experimental conditions produced the greatest mean fold change?


```R
df %>% 
group_by(Media, Strain, enrichment_method) %>%
summarize(mean_fold_diff=mean(concentration_fold_difference)) %>%
arrange(desc(mean_fold_diff)) %>%
head(1)
```
