---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.11.3
  kernelspec:
    display_name: Bash
    language: bash
    name: bash
---

# Making Generic Commands
Let's put the Bash shell to work for us by being smart with our variables

Load variables from bioinf_config.sh, make a new directory for output, and check that it looks OK.

```{bash}
source bioinf_config.sh
mkdir -p $GENERAL_TRIM_DIR $GENERAL_STAROUT_DIR
```

## Using a *FASTQ* variable
Most of the commands in our pipeline are complicated! To apply our pipeline to different FASTQs, we need to change things in multiple places.  For example, just to run trimming with fastq-mcf, we need to change things in two places between each run: the input FASTQ and the output FASTQ.  If we were doing this with paired-end reads, we would have to change four things. Doing this by hand is not only tedious, but error prone.  Doing almost the same thing repeatedly is something that people are bad at, but computers are very good at!  So let's get the computer to do the hard work.  Because the Bash shell is almost magical (it is a full fledged programming language), we can do this easily.

```{bash}
SRA_ACCESSION="A"
echo "RUNNING FASTQ: ~~~~${SRA_ACCESSION}~~~~"
echo "TRIMING: ${SRA_ACCESSION}"
echo "MAPPING: ${SRA_ACCESSION}"
```

The `for` loop in Bash is conceptually the same as in any other programming language, although the syntax may be different.  The `do` and `done` are essential - `do` needs to be before the "loop body" (what is going to be repeated) and `done` needs to be after it.

So let's try something almost useful:

```{bash}
SRA_ACCESSION="SRR12804466"
echo "RUNNING FASTQ: ~~~~${SRA_ACCESSION}~~~~"
echo "TRIMING: ${SRA_ACCESSION}"
echo "MAPPING: ${SRA_ACCESSION}"
```

## Now for the real thing . . .

Now we can apply this to actually running the trimming, filtering, and mapping.

### Let's run Trimmomatic:

```{bash}
SRA_ACCESSION="SRR12804466"
echo "---------------- TRIMMING: $SRA_ACCESSION ----------------"
TrimmomaticPE \
    -threads $TOTAL_THREADS \
    -phred33 \
    ${RAW_FASTQ_DIR}/${SRA_ACCESSION}_1.fastq.gz \
    ${RAW_FASTQ_DIR}/${SRA_ACCESSION}_2.fastq.gz \
    ${GENERAL_TRIM_DIR}/${SRA_ACCESSION}_1_trimmed.fastq.gz \
    ${GENERAL_TRIM_DIR}/${SRA_ACCESSION}_1_unpaired.fastq.gz \
    ${GENERAL_TRIM_DIR}/${SRA_ACCESSION}_2_trimmed.fastq.gz \
    ${GENERAL_TRIM_DIR}/${SRA_ACCESSION}_2_unpaired.fastq.gz \
    ILLUMINACLIP:TruSeq2-PE.fa:2:30:10:2:keepBothReads LEADING:3 TRAILING:3 MINLEN:36
```

### Now let's do the same thing for STAR

```{bash}
SRA_ACCESSION="SRR12804466"
echo "---------------- MAPPING: $SRA_ACCESSION ----------------"
STAR \
    --runMode alignReads \
    --twopassMode None \
    --genomeDir $GENOME_DIR \
    --readFilesIn ${GENERAL_TRIM_DIR}/${SRA_ACCESSION}_1_trimmed.fastq.gz ${GENERAL_TRIM_DIR}/${SRA_ACCESSION}_2_trimmed.fastq.gz \
    --readFilesCommand gunzip -c \
    --outFileNamePrefix ${GENERAL_STAROUT_DIR}/${SRA_ACCESSION}_ \
    --quantMode GeneCounts \
    --outSAMtype None \
    --runThreadN $TOTAL_THREADS
```

### And let's check the result

```{bash}
ls ${GENERAL_STAROUT_DIR}
```

By abstracting the code we can run these two steps on all the samples by only changing the value of `$SRA_ACCESSION`. But wait, it gets even better . . .
