---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.11.3
  kernelspec:
    display_name: Bash
    language: bash
    name: bash
---

# Quality Control

So far we have been working with only one FASTQ file, both for simplicity and for execution speed. This means that we have been treating our data as if it was single-end data, but it is is actually paired-end data. So let's use both pairs of reads. Processing paired-end data is a bit more complicated than single-end data, but not a lot. 

Let's load variables from bioinf_config.sh, make a new directory for output, and check that it looks OK.

```{bash}
source bioinf_config.sh

mkdir -p ${PE_QC}
ls $PE_OUT_DIR
```

## FastQC
FastQC doesn't know anything about paired-end data, so running it out paired-end FASTQ files is just like running it on multiple single-end FASTQs - just list both FASTQ files in the pair.

```{bash}
fastqc --threads $TOTAL_THREADS --extract --outdir $PE_QC $RAW_FASTQ_DIR/SRR12804466_1.fastq.gz $RAW_FASTQ_DIR/SRR12804466_2.fastq.gz 
```

## MultiQC
And MultiQC doesn't care either, just give it the directory where FastQC put its output and it loads the information from all the files that FastQC processed

```{bash}
multiqc $PE_QC --outdir $PE_QC
```

Once multiqc is done running we can view the results by finding the output in the Jupyter browser, it should be in a file named `multiqc_report.html` in :

```{bash}
echo $PE_QC
```
